#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Zsh options.
setopt extended_glob

fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
prompt pure

# Source zstyles you might use with antidote.
[[ -e ${ZDOTDIR:-~}/.zstyles ]] && source ${ZDOTDIR:-~}/.zstyles

# Clone antidote if necessary.
[[ -d ${ZDOTDIR:-~}/.antidote ]] ||
  git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

# Create an amazing Zsh config using antidote plugins.
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

export PATH=~/.cargo/bin:$PATH

export LS_COLORS="$(vivid generate molokai)"
#fnm
export PATH="./.fnm:$PATH"
eval "`fnm env`"

eval $(thefuck --alias)

# alias ls="ls --color=auto"
alias ls="eza"
alias tldr="tldr --color always"
