require'plugins.startup'
require'plugins.startup'
require'plugins.bufferline'
-- require'plugins.coq'
require'plugins.cmp'
require'plugins.color'
require'plugins.lsp_config'
require'plugins.indent_blankline'
require'plugins.custom'
require'plugins.auto_pair'
require'plugins.telescope'
require'plugins.nvim-treesister'
require'plugins.nvim_tree'
require'plugins.terminal'
require'plugins.comment'
require'plugins.statusline'
require'plugins.tabline'
require'plugins.session'
