local icons_set = require('plugins.lsp_config').icons_set
local extra_icon = require('plugins.lsp_config').extra

vim.g.symbols_outline = {
    highlight_hovered_item = false,
    -- show_guides = true,
    auto_preview = false,
    -- position = 'right',
    -- relative_width = true,
    -- width = 25,
    -- auto_close = false,
    -- show_numbers = false,
    -- show_relative_numbers = false,
    -- show_symbol_details = true,
    -- preview_bg_highlight = 'Pmenu',
    -- keymaps = { -- These keymaps can be a string or a table for multiple keys
    --     close = { '<Esc>', 'q' },
    --     goto_location = '<Cr>',
    --     focus_location = 'o',
    --     hover_symbol = '<C-space>',
    --     toggle_preview = 'K',
    --     rename_symbol = 'r',
    --     code_actions = 'a',
    -- },
    -- lsp_blacklist = {},
    -- symbol_blacklist = {},
    symbols = {
        Key = { icon = extra_icon.Lock, hl = 'TSType' },
        Namespace = { icon = '', hl = 'TSNamespace' },
        Null = { icon = extra_icon.Null, hl = 'TSType' },
        Number = { icon = '#', hl = 'TSNumber' },
        Object = { icon = '⦿', hl = 'TSType' },
        Package = { icon = '', hl = 'TSNamespace' },
        String = { icon = extra_icon.String, hl = 'TSString' },
        Array = { icon = '', hl = 'TSConstant' },
        Boolean = { icon = '⊨', hl = 'TSBoolean' },
        Class = { icon = icons_set.Class, hl = 'TSType' },
        Constant = { icon = icons_set.Constant, hl = 'TSConstant' },
        Constructor = { icon = icons_set.Constructor, hl = 'TSConstructor' },
        Enum = { icon = icons_set.Enum, hl = 'TSType' },
        EnumMember = { icon = icons_set.EnumMember, hl = 'TSField' },
        Event = { icon = icons_set.Event, hl = 'TSType' },
        Field = { icon = icons_set.Field, hl = 'TSField' },
        File = { icon = icons_set.File, hl = 'TSURI' },
        Function = { icon = icons_set.Function, hl = 'TSFunction' },
        Interface = { icon = icons_set.Interface, hl = 'TSType' },
        Method = { icon = icons_set.Method, hl = 'TSMethod' },
        Module = { icon = icons_set.Module, hl = 'TSNamespace' },
        Operator = { icon = icons_set.Operator, hl = 'TSOperator' },
        Property = { icon = icons_set.Property, hl = 'TSMethod' },
        Struct = { icon = icons_set.Struct, hl = 'TSType' },
        TypeParameter = { icon = icons_set.TypeParameter, hl = 'TSParameter' },
        Variable = { icon = icons_set.Variable, hl = 'TSConstant' },
    },
}
