anki:
    username: ENC[AES256_GCM,data:fO7eCv2Hb6t4g8PohOSbk0WPkDIw/Ro=,iv:ewJLdVgdKBh0Uw1quXQwnf3K+jGICzqaPMIVD7J7LeI=,tag:Vmd9kIxDwNakYqLZq6BeZg==,type:str]
    password: ENC[AES256_GCM,data:AV6U8yNU9FGtp4wvfeDGr/8mEeY=,iv:n63OjS184re8JxV5KlznU0jqHLG3cZaCzUSJ9hjl0Lw=,tag:5wV07/qpqAv1oSoSniXWKA==,type:str]
sops:
    age:
        - recipient: age1t6cdxzv6dgvv6408rsykkjz2hhhp6e5a8wa5x27eazzl67ezpsrqdmjr05
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZDFuSTF5V25lSWs1cTI2
            R0phWnJhaWhJVmM1RlgrazI4cmdzKzBCdldFCmFlZUpRRVZMRGFxVDV2NHN4TzNx
            aXpTdkpVMTNQUHVGTDBsRFcwV2xMN2cKLS0tIE5zYjVGOWsycDVNcXJQVVV0WnBF
            UTZ2VXhnZG9Cb1dHKytvekllbk9STVEKC6L1xyG8Q5etdETrbyR+r3c4gzst6vV2
            XdD+x+KilVU1WWtv97lvYinBdk8PUeCfm0bj2JfDwlM2zq4aeStLrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T17:11:16Z"
    mac: ENC[AES256_GCM,data:+XcaVWOLNx3sssEGZ+Bn4kRO/Z9Xrlw0mg+odmIPpKVE2d2UvcDqDiVzK15zlVktMeCm6rkq6JL6SSdYIde9KfsAMBucrhcxHGgZoZ1EuqWZJo4JsDJXJfmt0IWq/6tltIAFzqkLvnK3FpDQXeuudWg8EZ6Lrk3NdoA5BIV47AY=,iv:1gVmicNs6pGqHDBD3ZfyyvHWGjxMfEXZFvcZz4wxKG4=,tag:kO41VFnmo+c61oXggC8oHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
